name: Build OpenMU Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'


      - name: Restore
        shell: pwsh
        run: |
          dotnet restore src/MUnique.OpenMU.sln --runtime win-x64


      - name: Build
        shell: pwsh
        run: |
          dotnet build src/MUnique.OpenMU.sln `
            --configuration Release `
            --runtime win-x64 `
            --no-restore


      - name: Publish OpenMU
        shell: pwsh
        run: |
          dotnet publish `
            src/Startup/MUnique.OpenMU.Startup.csproj `
            --configuration Release `
            --runtime win-x64 `
            --self-contained true `
            --output publish/OpenMU `
            --no-build `
            /p:PublishTrimmed=false `
            /p:PublishSingleFile=false


      - name: Create Start Script
        shell: pwsh
        run: |
          @'
          @echo off
          cd /d "%~dp0"
          MUnique.OpenMU.Startup.exe
          pause
          '@ | Out-File publish/OpenMU/StartServer.bat -Encoding ascii


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenMU-Windows-x64
          path: publish/OpenMU
          retention-days: 30
